---
- name: Change the instance type
  vars:
    regions_list: "us-east-1"
    change_instance_to: "{{ change_instance_to }}"
  hosts: production
  serial: 1
  tasks:
    - name: Stop instance
      delegate_to: localhost
      ec2:
        region: "us-east-1"
        instance_ids: "{{ ansible_ec2_instance_id }}"
        state: stopped
        wait: true

    - name: Change instance type
      delegate_to: localhost
      shell: >
        aws ec2 modify-instance-attribute --instance-id {{ ansible_ec2_instance_id
        }}  --instance-type {{ change_instance_to}} --region us-east-1
      
    - name: Start instance
      delegate_to: localhost
      ec2:
        region: "us-east-1"
        instance_ids: "{{ ansible_ec2_instance_id }}"
        state: running
