---
- name: Install sonarqube
  hosts: all
  become: true
  tasks:
    - name: Docker install
      apt: 
        name: docker.io
        state: present
    - name: Installing python3
      apt:
        name: python3-pip
        state: present
    - name: Installing docker package using pip
      ansible.builtin.pip:
        name: docker
    - name: sonarqube Container Creating
      community.docker.docker_container:
        name: sonarqube
        image: sonarqube
        state: started
        ports:
        - "9000:9000"
        restart_policy: unless-stopped
