name: Docker NGINX Installation
on:
  push:
    branches:
      - main

jobs:
  docker_installation:
    runs-on: self-hosted  # Use a self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: sudo apt-get update && sudo apt-get install docker.io -y

      - name: Set up Docker daemon
        run: sudo systemctl start docker

  docker:
    runs-on: self-hosted  # Use a self-hosted runner
    needs: docker_installation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull NGINX Docker image
        run: sudo docker pull nginx

      - name: Remove old Docker container
        run: sudo docker rm -f nginx2

      - name: Run NGINX container
        run: |
          sudo docker run -d -p 80:80 --name nginx2 nginx
          sudo docker exec nginx2 sh -c "echo '<h1>GitHub Actions Build Number: $GITHUB_RUN_NUMBER</h1>' >> /usr/share/nginx/html/index.html"

      - name: Check NGINX status
        run: sudo docker ps -a

      - name: Test NGINX
        run: curl http://ifconfig.me
