name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on:  self-hosted

    steps:

      - name: Stage 1
        run: echo "Hello, world! - Stage 1"

  hello_world_job2:
    runs-on:  self-hosted
    steps:

      - name: Stage 10
        run: echo "Hello, world! - Stage 10"

      - name: Stage 2
        run: echo "Hello, world! - Stage 2"

      - name: Stage 3
        run: echo "Hello, world! - Stage 3"

      - name: Stage 4
        run: echo "Hello, world! - Stage 4"

      - name: Stage 5
        run: echo "Hello, world! - Stage 5"
