name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on:  self-hosted

    steps:

      - name: Test1
        run: echo "Hello, world! - Stage 1"

  hello_world_job2:
    runs-on:  self-hosted
    steps:

      - name: Test2
        run: echo "Hello, world! - Stage 10"

      - name: Test3
        run: echo "Hello, world! - Stage 2"

      - name: Test4
        run: echo "Hello, world! - Stage 3"

      - name: Test5
        run: echo "Hello, world! - Stage 4"

      - name: Test6
        run: echo "Hello, world! - Stage 5"
