name: Docker NGINX Installation
on:
  push:
    branches:
      - main

jobs:
  docker_installation:
    runs-on: self-hosted
    steps:
      - name: Install Docker
        run: sudo apt-get update && sudo apt-get install docker.io -y

      - name: Set up Docker daemon
        run: sudo systemctl start docker

  docker:
    runs-on: self-hosted
    steps:

      - name: Pull NGINX Docker image
        run: docker pull nginx

      - name: Run NGINX container
        run: |
          docker run -itd -p 80:80 --name nginx2 nginx

      - name: Check NGINX status
        run: docker ps -a

      - name: Test NGINX
        run: curl ifconfig.me
